# Generated by Django 4.0.3 on 2022-11-24 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('option_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calculator.option')),
                ('res_x', models.IntegerField()),
                ('res_y', models.IntegerField()),
                ('matrix_size', models.CharField(max_length=9)),
                ('pixel_size', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            bases=('calculator.option',),
        ),
        migrations.CreateModel(
            name='FlattReduc',
            fields=[
                ('option_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calculator.option')),
                ('times', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
            bases=('calculator.option',),
        ),
        migrations.CreateModel(
            name='Telescope',
            fields=[
                ('option_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calculator.option')),
                ('focal_length', models.IntegerField()),
                ('diameter', models.IntegerField()),
                ('focal_ratio', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            bases=('calculator.option',),
        ),
    ]
