# Generated by Django 4.0.3 on 2022-11-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='res_x',
            new_name='matrix_x',
        ),
        migrations.RenameField(
            model_name='camera',
            old_name='res_y',
            new_name='matrix_y',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='matrix_size',
        ),
        migrations.AddField(
            model_name='camera',
            name='resolution_x',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='resolution_y',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
