# Generated by Django 4.0.3 on 2022-11-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_rename_res_x_camera_matrix_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='matrix_x',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='camera',
            name='matrix_y',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
