# Generated by Django 4.1.3 on 2023-01-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_camera_matrix_x_alter_camera_matrix_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flattreduc',
            name='times',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
