# Generated by Django 4.1.3 on 2023-01-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_alter_flattreduc_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telescope',
            name='focal_ratio',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
