# Generated by Django 4.0.3 on 2022-11-19 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=32)),
                ('optic', models.CharField(max_length=32)),
                ('camera', models.CharField(max_length=32)),
                ('mount', models.CharField(max_length=32)),
                ('filters', models.CharField(max_length=32)),
                ('date', models.DateField()),
                ('sqml', models.CharField(max_length=32)),
                ('exposure_details', models.CharField(max_length=32)),
                ('acquisition', models.CharField(max_length=32)),
                ('processing', models.CharField(max_length=32)),
                ('info', models.CharField(max_length=1000)),
                ('annotation_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Acquisition',
            fields=[
                ('option_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='images.option')),
            ],
            bases=('images.option',),
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('option_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='images.option')),
            ],
            bases=('images.option',),
        ),
        migrations.CreateModel(
            name='ExposureDetail',
            fields=[
                ('option_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='images.option')),
            ],
            bases=('images.option',),
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('option_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='images.option')),
            ],
            bases=('images.option',),
        ),
        migrations.CreateModel(
            name='Mount',
            fields=[
                ('option_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='images.option')),
            ],
            bases=('images.option',),
        ),
        migrations.CreateModel(
            name='Optic',
            fields=[
                ('option_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='images.option')),
            ],
            bases=('images.option',),
        ),
        migrations.CreateModel(
            name='Processing',
            fields=[
                ('option_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='images.option')),
            ],
            bases=('images.option',),
        ),
    ]
