# Generated by Django 4.1.3 on 2023-01-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='acquisition',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='image',
            name='exposure_details',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='image',
            name='filters',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='image',
            name='processing',
            field=models.CharField(max_length=64),
        ),
    ]
