# Generated by Django 4.1.3 on 2023-01-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_image_acquisition_alter_image_exposure_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='camera',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='image',
            name='info',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='image',
            name='mount',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='optic',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='image',
            name='sqml',
            field=models.CharField(max_length=64),
        ),
    ]
